name: Publish Python Package

on:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build setuptools wheel twine

    - name: Build package
      run: |
        python3 -m build

    - name: Publish package
      run: |
        twine upload dist/* -u __token__ -p '${{ secrets.PYPI_TOKEN }}'

